### PR TITLE
:heavy_plus_sign: typescript definition

### PR DESCRIPTION
**Pull request by Guria**

### CODE REVIEW

**Comment by Guria** [comment]
Don't hurry to merge. I am trying to test it locally

**Comment by Guria** [comment]
Ok. Checked it. Works as intended for me.

**Comment by Guria** [comment]
sorry for spammy pushes

**Comment by deepsweet** [comment]
landed with v0.2.0

**Comment by deepsweet** [comment]
also you have to bump start-rebem-preset with `npm update`

**Pull request merged**
